name:             doctest
version:          0.18.1
synopsis:         Test interactive Haskell examples
description: |
  The doctest program checks examples in source code comments.  It is modeled
  after doctest for Python (<https://docs.python.org/3/library/doctest.html>).

  Documentation is at <https://github.com/martijnbastiaan/doctest#readme>.
category:         Testing
license:          MIT
copyright:        (c) 2009-2018 Simon Hengel, 2021 Martijn Bastiaan
author:           Martijn Bastiaan <martijn@hmbastiaan.nl>
maintainer:       Martijn Bastiaan <martijn@hmbastiaan.nl>


github: martijnbastiaan/doctest

tested-with:
- GHC == 8.0.2
- GHC == 8.2.2
- GHC == 8.4.4
- GHC == 8.6.5
- GHC == 8.8.4
- GHC == 8.10.4
- GHC == 9.0.1

extra-source-files:
- example/**/*
- CHANGES.markdown
- README.markdown

ghc-options: -Wall

dependencies:
- base >= 4.8 && < 5
- base-compat >= 0.7.0
- Cabal
- cabal-install-parsers
- code-page >= 0.1
- containers
- deepseq
- directory
- exceptions
- filepath
- Glob
- pretty
- ghc >= 7.10 && < 9.1
- ghc-paths >= 0.1.0.9
- process
- syb >= 0.3
- transformers
- unordered-containers

library:
  source-dirs:
  - src
  - ghci-wrapper/src
  exposed-modules:
  - Test.DocTest
  - Test.DocTest.Helpers

tests:
  spec:
    main: Spec.hs
    ghc-options: -threaded
    cpp-options: -DTEST
    source-dirs:
      - test
      - src
      - ghci-wrapper/src
    c-sources: test/integration/with-cbits/foo.c
    dependencies:
    - HUnit
    - hspec         >= 2.3.0
    - hspec-core    >= 2.3.0
    - QuickCheck    >= 2.13.1
    - stringbuilder >= 0.4
    - silently      >= 1.2.4
    - setenv
    - mockery

  doctests:
    main: doctests.hs
    other-modules: []
    ghc-options: -threaded
    source-dirs: test
    dependencies: doctest
